### ISSUE TITLE
Unable to copy/paste from Pass to anything else

### ISSUE THREAD

**Issue by sorinfatu** [flathub/me.proton.Pass#37]
Clicking on a username or password field is supposed to copy the contents to the clipboard to paste in another app.
At this time clicking those fields gives a toast in the app that it has been copied but it can't be pasted anywhere else.

This happens in Bazzite (gnome and kde) on wayland with no additional layers. 

It does not happen in Fedora, openSUSE with the rpm version, Arch with the AUR version, Aeon Desktop with the rpm version installed in a distrobox (all of these on wayland as well) - so it is a flatpak only issue.

I have been looking at the permissions that are set for bitwarden  (since they had a similar issue some time ago) and testing the permissions they have vs pass.

It seems `socket=fallback-x11` is the issue. Unsetting it and setting `socket=x11` fixes the issue with copy/paste from the app. The username or password is actually copied to the clipboard and can be pasted in other apps.

A single odd issue remains - it can be pasted using Ctr-V or the right click menu but not using the wheel to click.

**Comment by calexandru2018** [comment]
Also happens on Fedora 41 for me

**Comment by Amourspirit** [comment]
Happens on Ubuntu 24.04 for me.

**Comment by henrik-wittenberg** [comment]
Also happens on Solus 4.7 (Gnome 47/Wayland) for me.

I turned off "socket=fallback-x11" via FlatSeal  ("socket=x11" was also already turned on) and copy & pate now works for me.

**Comment by ErikReider** [comment]
Same issue here with none of the previously stated fixes working for me on Fedora 41 and Sway

**Comment by complexspaces** [comment]
Upon another look, I think the original issue may have been that ProtonPass didn't set enable `arboard`'s `wayland-data-control` feature at the time this issue was opened. It look like @proletarius101 fixed this 4 days after the last update to this issue in https://github.com/ProtonMail/WebClients/commit/e7b33dc141c3d30947f5c624122bc0e85e2f1dbc.

Given that, my recommendation would be to try reverting #59 as long as the upstream version with the change to enable the Wayland feature flag has made it into this distribution already.

**Comment by proletarius101** [comment]
> If so I'm not sure the depended upon issue is the right one since that report is talking about code that is not executed in supported Wayland environments.

Yes, it seems that the code works only on X11, for some reasons.

**Comment by proletarius101** [comment]
Relevant logs:

```
❯ flatpak run --env=WAYLAND_DEBUG=1 --command=sh me.proton.Pass -c 'WAYLAND_DEBUG=client /app/bin/start-proton-pass 2>&1 | egrep -i "data_control|zwlr|wl_data_device_manager|primary_selection|zwp_primary_selection" -n || true'
egrep: warning: egrep is obsolescent; using grep -E
11:[ 270162.602] wl_registry#2.global(6, "wl_data_device_manager", 3)
12:[ 270162.609]  -> wl_registry#2.bind(6, "wl_data_device_manager", 3, new id [unknown]#7)
15:[ 270162.634] wl_registry#2.global(8, "zwp_primary_selection_device_manager_v1", 1)
16:[ 270162.648]  -> wl_registry#2.bind(8, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]#9)
33:[ 270162.773]  -> wl_data_device_manager#7.get_data_device(new id wl_data_device#17, wl_seat#16)
178:[ 270212.196] {Default Queue} wl_registry#2.global(6, "wl_data_device_manager", 3)
179:[ 270212.200] {Default Queue}  -> wl_registry#2.bind(6, "wl_data_device_manager", 3, new id [unknown]#8)
181:[ 270212.205] {Default Queue} wl_registry#2.global(8, "zwp_primary_selection_device_manager_v1", 1)
182:[ 270212.207] {Default Queue}  -> wl_registry#2.bind(8, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]#9)
246:[ 270245.377] {Default Queue}  -> zwp_primary_selection_device_manager_v1#9.get_device(new id zwp_primary_selection_device_v1#29, wl_seat#27)
247:[ 270245.408] {Default Queue}  -> wl_data_device_manager#8.get_data_device(new id wl_data_device#30, wl_seat#27)
325:[ 270375.591]  -> zwp_primary_selection_device_manager_v1#9.get_device(new id zwp_primary_selection_device_v1#52, wl_seat#16)
470:[ 270761.738] zwp_primary_selection_device_v1#52.data_offer(new id zwp_primary_selection_offer_v1#4278190081)
471:[ 270761.742] zwp_primary_selection_offer_v1#4278190081.offer("STRING")
472:[ 270761.743] zwp_primary_selection_offer_v1#4278190081.offer("TEXT")
473:[ 270761.745] zwp_primary_selection_offer_v1#4278190081.offer("UTF8_STRING")
474:[ 270761.747] zwp_primary_selection_offer_v1#4278190081.offer("text/plain;charset=utf-8")
475:[ 270761.749] zwp_primary_selection_offer_v1#4278190081.offer("text/plain")
476:[ 270761.750] zwp_primary_selection_offer_v1#4278190081.offer("text/plain;charset=utf-8")
477:[ 270761.752] zwp_primary_selection_device_v1#52.selection(zwp_primary_selection_offer_v1#4278190081)
1405:[ 276303.898] zwp_primary_selection_device_v1#52.data_offer(new id zwp_primary_selection_offer_v1#4278190083)
1406:[ 276303.902]  -> zwp_primary_selection_offer_v1#4278190081.destroy()
1407:[ 276303.904] zwp_primary_selection_offer_v1#4278190083.offer("STRING")
1408:[ 276303.906] zwp_primary_selection_offer_v1#4278190083.offer("TEXT")
1409:[ 276303.908] zwp_primary_selection_offer_v1#4278190083.offer("UTF8_STRING")
1410:[ 276303.910] zwp_primary_selection_offer_v1#4278190083.offer("text/plain;charset=utf-8")
1411:[ 276303.911] zwp_primary_selection_offer_v1#4278190083.offer("text/plain")
1412:[ 276303.913] zwp_primary_selection_offer_v1#4278190083.offer("text/plain;charset=utf-8")
1413:[ 276303.915] zwp_primary_selection_device_v1#52.selection(zwp_primary_selection_offer_v1#4278190083)
2355:[ 278094.799] zwp_primary_selection_device_v1#52.data_offer(new id zwp_primary_selection_offer_v1#4278190080)
2356:[ 278094.805]  -> zwp_primary_selection_offer_v1#4278190083.destroy()
2357:[ 278094.809] zwp_primary_selection_offer_v1#4278190080.offer("STRING")
2358:[ 278094.812] zwp_primary_selection_offer_v1#4278190080.offer("TEXT")
2359:[ 278094.815] zwp_primary_selection_offer_v1#4278190080.offer("UTF8_STRING")
2360:[ 278094.817] zwp_primary_selection_offer_v1#4278190080.offer("text/plain;charset=utf-8")
2361:[ 278094.820] zwp_primary_selection_offer_v1#4278190080.offer("text/plain")
2362:[ 278094.823] zwp_primary_selection_offer_v1#4278190080.offer("text/plain;charset=utf-8")
2363:[ 278094.826] zwp_primary_selection_device_v1#52.selection(zwp_primary_selection_offer_v1#4278190080)
8671:[ 286084.405][rs] <- wl_registry@2.global, (6, Some("wl_data_device_manager"), 3)
8673:[ 286084.629][rs] <- wl_registry@2.global, (8, Some("zwp_primary_selection_device_manager_v1"), 1)
```

```
❯ flatpak run --env=WAYLAND_DEBUG=1 com.bitwarden.desktop 2>&1 | egrep -i "data_control|zwlr|wl_data_device_manager|primary_selection" -n || true
16:[ 343813.533] wl_registry#2.global(6, "wl_data_device_manager", 3)
17:[ 343813.536]  -> wl_registry#2.bind(6, "wl_data_device_manager", 3, new id [unknown]#7)
20:[ 343813.547] wl_registry#2.global(8, "zwp_primary_selection_device_manager_v1", 1)
21:[ 343813.549]  -> wl_registry#2.bind(8, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]#9)
37:[ 343813.596]  -> wl_data_device_manager#7.get_data_device(new id wl_data_device#16, wl_seat#15)
346:[ 343823.716] {Default Queue} wl_registry#2.global(6, "wl_data_device_manager", 3)
347:[ 343823.721] {Default Queue}  -> wl_registry#2.bind(6, "wl_data_device_manager", 3, new id [unknown]#8)
349:[ 343823.725] {Default Queue} wl_registry#2.global(8, "zwp_primary_selection_device_manager_v1", 1)
350:[ 343823.727] {Default Queue}  -> wl_registry#2.bind(8, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]#9)
414:[ 343863.027] {Default Queue}  -> zwp_primary_selection_device_manager_v1#9.get_device(new id zwp_primary_selection_device_v1#29, wl_seat#27)
415:[ 343863.037] {Default Queue}  -> wl_data_device_manager#8.get_data_device(new id wl_data_device#30, wl_seat#27)
494:[ 344131.410]  -> zwp_primary_selection_device_manager_v1#9.get_device(new id zwp_primary_selection_device_v1#42, wl_seat#15)
579:[ 344294.782] zwp_primary_selection_device_v1#42.data_offer(new id zwp_primary_selection_offer_v1#4278190081)
580:[ 344294.786] zwp_primary_selection_offer_v1#4278190081.offer("STRING")
581:[ 344294.789] zwp_primary_selection_offer_v1#4278190081.offer("TEXT")
582:[ 344294.791] zwp_primary_selection_offer_v1#4278190081.offer("UTF8_STRING")
583:[ 344294.794] zwp_primary_selection_offer_v1#4278190081.offer("text/plain;charset=utf-8")
584:[ 344294.796] zwp_primary_selection_offer_v1#4278190081.offer("text/plain")
585:[ 344294.798] zwp_primary_selection_offer_v1#4278190081.offer("text/plain;charset=utf-8")
586:[ 344294.801] zwp_primary_selection_device_v1#42.selection(zwp_primary_selection_offer_v1#4278190081)
1777:[ 350618.951] zwp_primary_selection_device_v1#42.data_offer(new id zwp_primary_selection_offer_v1#4278190083)
1778:[ 350618.955]  -> zwp_primary_selection_offer_v1#4278190081.destroy()
1779:[ 350618.957] zwp_primary_selection_offer_v1#4278190083.offer("text/plain;charset=utf-8")
1780:[ 350618.959] zwp_primary_selection_device_v1#42.selection(zwp_primary_selection_offer_v1#4278190083)
2137:[ 354151.762] zwp_primary_selection_device_v1#42.data_offer(new id zwp_primary_selection_offer_v1#4278190080)
2138:[ 354151.771]  -> zwp_primary_selection_offer_v1#4278190083.destroy()
2139:[ 354151.776] zwp_primary_selection_offer_v1#4278190080.offer("text/plain;charset=utf-8")
2140:[ 354151.781] zwp_primary_selection_device_v1#42.selection(zwp_primary_selection_offer_v1#4278190080)
2820:[ 355170.602]  -> zwp_primary_selection_device_manager_v1#9.create_source(new id zwp_primary_selection_source_v1#50)
2821:[ 355170.616]  -> zwp_primary_selection_source_v1#50.offer("STRING")
2822:[ 355170.619]  -> zwp_primary_selection_source_v1#50.offer("TEXT")
2823:[ 355170.621]  -> zwp_primary_selection_source_v1#50.offer("UTF8_STRING")
2824:[ 355170.624]  -> zwp_primary_selection_source_v1#50.offer("text/plain")
2825:[ 355170.626]  -> zwp_primary_selection_source_v1#50.offer("text/plain;charset=utf-8")
2826:[ 355170.629]  -> zwp_primary_selection_source_v1#50.offer("text/plain;charset=utf-8")
2827:[ 355170.635]  -> zwp_primary_selection_device_v1#42.set_selection(zwp_primary_selection_source_v1#50, 39355)
2828:[ 355171.379] zwp_primary_selection_device_v1#42.data_offer(new id zwp_primary_selection_offer_v1#4278190083)
2829:[ 355171.406]  -> zwp_primary_selection_offer_v1#4278190080.destroy()
2830:[ 355171.413] zwp_primary_selection_offer_v1#4278190083.offer("text/plain;charset=utf-8")
2831:[ 355171.416] zwp_primary_selection_offer_v1#4278190083.offer("text/plain;charset=utf-8")
2832:[ 355171.418] zwp_primary_selection_offer_v1#4278190083.offer("text/plain")
2833:[ 355171.420] zwp_primary_selection_offer_v1#4278190083.offer("UTF8_STRING")
2834:[ 355171.421] zwp_primary_selection_offer_v1#4278190083.offer("TEXT")
2835:[ 355171.423] zwp_primary_selection_offer_v1#4278190083.offer("STRING")
2836:[ 355171.425] zwp_primary_selection_device_v1#42.selection(zwp_primary_selection_offer_v1#4278190083)
2854:[ 355421.000]  -> wl_data_device_manager#7.create_data_source(new id wl_data_source#51)
2864:[ 355421.039]  -> zwp_primary_selection_device_manager_v1#9.create_source(new id zwp_primary_selection_source_v1#49)
2865:[ 355421.044]  -> zwp_primary_selection_source_v1#50.destroy()
2866:[ 355421.047]  -> zwp_primary_selection_source_v1#49.offer("STRING")
2867:[ 355421.049]  -> zwp_primary_selection_source_v1#49.offer("TEXT")
2868:[ 355421.051]  -> zwp_primary_selection_source_v1#49.offer("UTF8_STRING")
2869:[ 355421.052]  -> zwp_primary_selection_source_v1#49.offer("text/plain")
2870:[ 355421.054]  -> zwp_primary_selection_source_v1#49.offer("text/plain;charset=utf-8")
2871:[ 355421.056]  -> zwp_primary_selection_source_v1#49.offer("text/plain;charset=utf-8")
2872:[ 355421.060]  -> zwp_primary_selection_device_v1#42.set_selection(zwp_primary_selection_source_v1#49, 39357)
2886:[ 355421.337] zwp_primary_selection_device_v1#42.selection(nil)
2887:[ 355421.340]  -> zwp_primary_selection_offer_v1#4278190083.destroy()
2888:[ 355421.351] zwp_primary_selection_device_v1#42.data_offer(new id zwp_primary_selection_offer_v1#4278190082)
2889:[ 355421.353] zwp_primary_selection_offer_v1#4278190082.offer("text/plain;charset=utf-8")
2890:[ 355421.355] zwp_primary_selection_offer_v1#4278190082.offer("text/plain;charset=utf-8")
2891:[ 355421.357] zwp_primary_selection_offer_v1#4278190082.offer("text/plain")
2892:[ 355421.359] zwp_primary_selection_offer_v1#4278190082.offer("UTF8_STRING")
2893:[ 355421.360] zwp_primary_selection_offer_v1#4278190082.offer("TEXT")
2894:[ 355421.362] zwp_primary_selection_offer_v1#4278190082.offer("STRING")
2895:[ 355421.364] zwp_primary_selection_device_v1#42.selection(zwp_primary_selection_offer_v1#4278190082)
```

**Comment by proletarius101** [comment]
according to https://github.com/bitwarden/clients/issues/13431#issuecomment-2974706750, GNOME is not supported

**Comment by mati865** [comment]
Some of the compositors block `ext-data-control-v1` and `wlr-data-control-v1` for sandboxed applications: https://github.com/niri-wm/niri/blob/38191826cb1e5fb9051a7e141fefe4941a2b4bed/docs/wiki/Security-Model.md

This breaks copying when using Pass flatpak, but system installed one works fine. At least COSMIC Desktop and Niri are affected.

**Comment by proletarius101** [comment]
> Some of the compositors block `ext-data-control-v1` and `wlr-data-control-v1` for sandboxed applications: https://github.com/niri-wm/niri/blob/38191826cb1e5fb9051a7e141fefe4941a2b4bed/docs/wiki/Security-Model.md
> 
> This breaks copying when using Pass flatpak, but system installed one works fine. At least COSMIC Desktop and Niri are affected.

It actually has nothing to do with sandboxing or Flatpak. It's about the lack of support for Wayland in their copy library.

**Comment by mati865** [comment]
To reiterate with more details:
This and other password related apps when running using Wayland, rely on `arboard` with feature `wayland-data-control`. That routes clipboard actions through `wl-clipboard-rs` crate, which uses `ext-data-control-v1` and `wlr-data-control-v1` protocols.

Then another protocol comes into play called `security-context-v1`. It's literally created to identify sandboxed applications like Flatpaks: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/security-context/engines.md#flatpak

Since data control protocols are potentially dangerous, access to them is limited for apps identified as sandboxed by `security-context-v1` protocol: https://github.com/pop-os/cosmic-comp/blob/b955789a4e797a54897d7c584529e7f00b781f9f/src/state.rs#L692
This is fine because these protocols are meant for CLI and clipboard managers, not for GUI. However, this makes `arboard`'s workaround via `wayland-data-control` ineffective when Proton Pass is sandboxed.

The proper solution is to use the protocol designed for that: `wl_data_device`, but it's still missing: https://github.com/1Password/arboard/pull/209.

**Comment by complexspaces** [comment]
> The proper solution is to use the protocol designed for that: wl_data_device, but it's still missing

This is something that is being investigated in `arboard`, FWIW.

However I do want to at least mention that I don't see `wl_data_device` as an equivalent/better protocol, coming from both the angle of clipboard library developer and as a password manager user who wants rich feature support and implementation flexibility.

**Comment by proletarius101** [comment]
@mati865 @complexspaces 

For https://github.com/1Password/arboard/pull/209, more guidance on the implementation is actually wanted, since I'm not an expert of compositors nor Rust.

**Comment by proletarius101** [comment]
Seems like https://github.com/flathub/me.proton.Pass/pull/102 fixes the issue. Let me know if it doesn't.

**Comment by Huluti** [comment]
Yes it works!!! Thanks

**Comment by mati865** [comment]
Thanks, works nicely in COSMIC.

**Comment by mati865** [comment]
> Thanks, works nicely in COSMIC.

Oops, I was too hastily with that. When I upgraded Proton Pass it wasn't the latest version but https://github.com/flathub/me.proton.Pass/pull/101

I was wondering how it does work despite missing Clipboard API in COSMIC's Portal, but was happy enough with the outcome not to investigate further.

Latest version once more breaks unless manually forcing X11, so here comes the answer to my question: it doesn't.
Although the Portal seems like the best solution to me if it indeed works in DE that support it, so the issue should be tracked in the problematic DE's Portal implementations.
Here is the one for COSMIC: https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/177

**Comment by proletarius101** [comment]
I suspect that as https://github.com/bitwarden/clients/issues/13431#issuecomment-4439342912 indicated, it worked only because both `--socket=x11` and `--socket=wayland` were present and allowed the fallback of arboard itself. The Electron part stayed on Wayland. That was consistent with `xlsclients` not showing `Proton Pass`.  But that was not actually allowed on Flathub.

**Comment by Huluti** [comment]
[libportal 0.10.0](https://github.com/flatpak/libportal/releases/tag/0.10.0) has added a clipboard API, does this  could help this issue?

**Comment by IvanVeloz** [comment]
>  it worked only because both --socket=x11 and --socket=wayland were present and allowed the fallback of arboard itself

I can reproduce this behavior on Gnome 50, Bluefin latest.

**Comment by JKxZ** [comment]
I can reproduce this problem on Rocky Linux 10. I have the 1.38.1 flathub version installed that was updated on 7/9/2026.

This was not presenting with the rpm install on version 1.38.0.

**Comment by watchdominiondotcom** [comment]
on arch i was not having this issue using kde but on pop os cosmic i am having the same issue as everyone and i already tinkered and troubleshot using flatseal etc

**Comment by Stensel8** [comment]
Same on Bazzite. 

`flatpak override --user --socket=x11 --nosocket=fallback-x11 me.proton.Pass
`

solved it.
However, it would be better to get it fixed in the app itself.

**Comment by tails618** [comment]
That didn't seem to fix it for me on Bluefin (similarly to Bazzite, also atomic and also part of Universal Blue). Nor does the above from @fugolmere (I don't remember if that worked back in March, sorry).

**Comment by proletarius101** [comment]
I'll address the issue the same way as to how bitwarden did it.

Refs:
- https://github.com/flathub-infra/flatpak-builder-lint/blob/4a239bb4ff875a196a6cc6f6a1ce314e58240b47/flatpak_builder_lint/staticfiles/exceptions.json#L415
- https://github.com/flathub/com.bitwarden.desktop/blob/b25ca452aeea219172db5bda273c63efb5cfb7ce/com.bitwarden.desktop.yaml#L11
- https://matrix.to/#/!xFJJgxGKItHQPfstha:matrix.org/$5njH_vdIlUfQMn-fTekptgj8widPr0KRwzEK0qfG1Ds?via=matrix.org&via=gnome.org&via=mozilla.org

**Comment by Stensel8** [comment]
> I'll address the issue the same way as to how bitwarden did it.
> 
> Refs:
> 
> * https://github.com/flathub-infra/flatpak-builder-lint/blob/4a239bb4ff875a196a6cc6f6a1ce314e58240b47/flatpak_builder_lint/staticfiles/exceptions.json#L415
> * https://github.com/flathub/com.bitwarden.desktop/blob/b25ca452aeea219172db5bda273c63efb5cfb7ce/com.bitwarden.desktop.yaml#L11
> * https://matrix.to/#/!xFJJgxGKItHQPfstha:matrix.org/$5njH_vdIlUfQMn-fTekptgj8widPr0KRwzEK0qfG1Ds?via=matrix.org&via=gnome.org&via=mozilla.org

Let us know. Thanks!

**Comment by cortezbuilds** [comment]
Confirmed on Pop!_OS 24.04 COSMIC/Wayland with the Flathub build `me.proton.Pass` 1.40.0. Clicking a username/password showed the “copied” toast, but the clipboard retained its previous value. Proton Pass Autotype also performed no insertion. Ordinary keyboard copy/paste worked, so this was not an XKB mapping problem.

I installed Proton's checksum-verified native Debian package 1.40.2 and granted COSMIC's remote-interaction permission when prompted. Both click-to-copy and Autotype then worked immediately. I removed the Flatpak without deleting its application data. This is a useful workaround confirmation, not evidence that the Flatpak/portal defect is fixed.

COSMIC's related portal report is pop-os/cosmic-epoch#3830, currently closed as a duplicate.
